from __future__ import annotations
from itertools import product
import numpy as np
import pandas as pd
from utils import ntile, zscore_cross_section


def node_names(tree_depth: int, q_num: int = 2) -> list[str]:
    nodes = ["1"]
    frontier = ["1"]
    for _ in range(tree_depth):
        nxt = []
        for n in frontier:
            for b in range(1, q_num + 1):
                child = f"{n}{b}"
                nodes.append(child)
                nxt.append(child)
        frontier = nxt
    return nodes


def assign_tree_paths_for_sequence(
    df_month: pd.DataFrame,
    feat_sequence: tuple[str, ...],
    q_num: int = 2,
) -> pd.DataFrame:
    """Recursive AP-tree stock assignment for one feature order."""
    df = df_month.copy()
    df["path"] = "1"
    active = ["1"]
    for feat in feat_sequence:
        nxt = []
        for node in active:
            mask = df["path"].eq(node)
            if mask.sum() == 0:
                continue
            buckets = ntile(df.loc[mask, feat], q_num)
            for b in range(1, q_num + 1):
                child = f"{node}{b}"
                child_idx = buckets.index[buckets.eq(b).fillna(False)]
                df.loc[child_idx, "path"] = child
                nxt.append(child)
        active = nxt
    return df


def _node_return_and_weights(
    node_df: pd.DataFrame,
    node_id: str,
    tau: float,
    signal_col: str,
    ret_col: str = "ret",
    size_col: str = "size",
) -> tuple[dict, pd.DataFrame]:
    d = node_df.copy()
    d = d[d[ret_col].notna() & d[size_col].notna() & (d[size_col] > 0)].copy()
    if d.empty:
        stats = {
            "node_id": node_id,
            "baseline_ret": np.nan,
            "tilt_ret": np.nan,
            "n_stocks": 0,
            "within_node_tilt_l1": np.nan,
        }
        return stats, pd.DataFrame()

    d["base_stock_w"] = d[size_col].astype(float) / d[size_col].astype(float).sum()
    z = zscore_cross_section(d[signal_col].astype(float).fillna(0.0))
    raw = d["base_stock_w"] * np.exp(tau * z)
    d["tilt_stock_w"] = raw / raw.sum()
    stats = {
        "node_id": node_id,
        "baseline_ret": float((d["base_stock_w"] * d[ret_col].astype(float)).sum()),
        "tilt_ret": float((d["tilt_stock_w"] * d[ret_col].astype(float)).sum()),
        "n_stocks": int(len(d)),
        "within_node_tilt_l1": float(np.abs(d["tilt_stock_w"] - d["base_stock_w"]).sum()),
    }
    keep = ["date", "date_dt", "yy", "mm", "permno", "ret", "size", signal_col]
    keep = [c for c in keep if c in d.columns]
    wdf = d[keep + ["base_stock_w", "tilt_stock_w"]].copy()
    wdf["node_id"] = node_id
    return stats, wdf


def build_all_ap_tree_candidate_returns(
    panel: pd.DataFrame,
    chars: list[str],
    tree_depth: int,
    tau: float,
    q_num: int = 2,
    signal_col: str = "residual_mom",
    deduplicate: bool = True,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Generate the full AP-tree candidate set.

    Matches the R structure where all feature-order trees are generated by expand.grid over
    n_feats^tree_depth and each tree contributes all nodes across levels.
    """
    sequences = list(product(chars, repeat=tree_depth))
    nodes = node_names(tree_depth, q_num=q_num)

    rows = []
    stat_rows = []
    weight_rows = []

    for (yy, mm), df_m0 in panel.groupby(["yy", "mm"], sort=True):
        date = df_m0["date"].iloc[0] if "date" in df_m0.columns else np.nan
        date_dt = df_m0["date_dt"].iloc[0] if "date_dt" in df_m0.columns else pd.NaT
        row = {"date": date, "date_dt": date_dt, "yy": int(yy), "mm": int(mm)}

        for s_idx, seq in enumerate(sequences, start=1):
            assigned = assign_tree_paths_for_sequence(df_m0, seq, q_num=q_num)
            seq_code = "".join(str(chars.index(f) + 1) for f in seq)
            for node in nodes:
                members = assigned[assigned["path"].str.startswith(node)]
                node_id = f"T{seq_code}_N{node}"
                stats, wdf = _node_return_and_weights(
                    members, node_id=node_id, tau=tau, signal_col=signal_col
                )
                row[f"baseline_{node_id}"] = stats["baseline_ret"]
                row[f"tilt_{node_id}"] = stats["tilt_ret"]
                stat_rows.append({"date": date, "date_dt": date_dt, "yy": int(yy), "mm": int(mm), **stats})
                if not wdf.empty:
                    weight_rows.append(wdf)
        rows.append(row)

    candidate_returns = pd.DataFrame(rows).sort_values(["yy", "mm"]).reset_index(drop=True)
    node_stats = pd.DataFrame(stat_rows)
    stock_weights = pd.concat(weight_rows, ignore_index=True) if weight_rows else pd.DataFrame()

    if deduplicate:
        candidate_returns = deduplicate_candidate_columns(candidate_returns)

    return candidate_returns, stock_weights, node_stats


def deduplicate_candidate_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Drop duplicate baseline columns among baseline set and duplicate tilt columns among tilt set."""
    meta = [c for c in ["date", "date_dt", "yy", "mm"] if c in df.columns]
    out = df[meta].copy()
    for prefix in ["baseline_", "tilt_"]:
        cols = [c for c in df.columns if c.startswith(prefix)]
        if not cols:
            continue
        mat = df[cols].fillna(0.0).T
        keep_mask = ~mat.duplicated()
        keep_cols = list(mat.index[keep_mask])
        out = pd.concat([out, df[keep_cols]], axis=1)
    return out


def select_candidate_matrix(candidate_returns: pd.DataFrame, prefix: str = "tilt_") -> pd.DataFrame:
    """Return date metadata plus selected candidate-return columns renamed port_*."""
    meta = [c for c in ["date", "date_dt", "yy", "mm"] if c in candidate_returns.columns]
    cols = [c for c in candidate_returns.columns if c.startswith(prefix)]
    if not cols:
        raise ValueError(f"No candidate columns found with prefix={prefix!r}")
    out = candidate_returns[meta + cols].copy()
    rename = {c: "port_" + c[len(prefix):] for c in cols}
    return out.rename(columns=rename)
